targets:
  $default:
    builders:
      # Freezed builder configuration
      freezed:
        enabled: true
        generate_for:
          - lib/**/*.dart
          - test/**/*.dart
        options:
          # Union types and sealed classes
          union_key: 'type'
          union_value_case: 'FreezedUnionCase.pascal'
          # Add copyWith and toString
          mutable: false
          # Run before json_serializable
        runs_before:
          - json_serializable
      
      # JSON Serializable builder configuration
      json_serializable:
        enabled: true
        generate_for:
          - lib/**/*.dart
          - test/**/*.dart
        options:
          # Generate both toJson and fromJson
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
          nullable: true
          
      # Riverpod generator configuration
      riverpod_generator:
        enabled: true
        generate_for:
          - lib/**/*.dart
          - test/**/*.dart

# Global builder options
global_options:
  # Freezed global options
  freezed:
    runs_before:
      - json_serializable
  
  # Build runner options
  build_runner:
    build_extensions:
      "^lib/{{}}.dart":
        - "lib/{{}}.g.dart"
        - "lib/{{}}.freezed.dart"